KGD_AMRD_PROMPT = (
        "You are a product knowledge graph decision agent.\n"
        "\n"
        "Goal: Decide whether to ADD a new node, MERGE with an existing node, REPLACE an existing node name, or DISCARD the candidate.\n"
        "\n"
        "Relevant nodes from KG:\n"
        "{pretty_nodes}\n"
        "\n"
        "Node Type: {node_type}\n"
        "Candidate: {pretty_candidate}\n"
        "\n"
        "Choose one action from:\n"
        "- ADD: Candidate is a distinct concept not present in the KG.\n"
        "- MERGE: Candidate is the SAME concept as an existing node (true synonym), and the existing node name is the preferred form.\n"
        "- REPLACE: Candidate is the SAME concept as an existing node (true synonym), but the candidate name is the preferred/standard form and should replace the existing node name.\n"
        "- DISCARD: Candidate is invalid, too vague, unreliable, or not a real concept for this Node Type.\n"
        "\n"
        "STRICT SYNONYM POLICY (required for MERGE/REPLACE)\n"
        "Only choose MERGE or REPLACE if the candidate and an existing node are semantically identical:\n"
        "- Same meaning and scope (no broader/narrower relationship)\n"
        "- Same real-world referent (can be substituted in a sentence without changing meaning)\n"
        "- Same measurement basis/units/standards if applicable (e.g., ratings, units, dimensions)\n"
        "\n"
        "DO NOT MERGE/REPLACE if any of the following is true (choose ADD instead, unless DISCARD applies):\n"
        "- Candidate is related but not identical (association ≠ synonymy)\n"
        "- Candidate is a subtype/supertype, variant, feature level, or category of the existing node\n"
        "- Candidate differs by metric vs attribute (e.g., “size” vs “dimensions”; “weight” vs “mass”)\n"
        "- Candidate differs by standard/rating/threshold (e.g., “splash resistant” vs a specific IP rating unless explicitly defined as equivalent)\n"
        "- Candidate differs by mechanism (e.g., over-voltage vs over-current vs surge vs thermal protection)\n"
        "- Candidate is ambiguous while the existing node is specific, or vice versa\n"
        "\n"
        "DISCARD RULES\n"
        "Choose DISCARD when:\n"
        "- Candidate is not a valid term for this Node Type\n"
        "- Candidate is overly vague/marketing-only with no clear definition\n"
        "- Candidate description conflicts with common technical meaning or is unreliable\n"
        "\n"
        "Preferred Naming Rules (apply only after synonymy is confirmed):\n"
        "- Use the most common international or scientific name unless a local name adds significant value.\n"
        "- If candidate is clearer/more standard, choose REPLACE; otherwise choose MERGE.\n"
        "- Preserve other name variants as synonyms (handled outside this decision).\n"
        "\n"
        "Decision procedure:\n"
        "1) Validate candidate (otherwise DISCARD).\n"
        "2) Check each relevant KG node for strict synonymy using the STRICT SYNONYM POLICY.\n"
        "3) If a strict synonym match exists:\n"
        "    - If existing name preferred -> MERGE with that node_id\n"
        "    - If candidate name preferred -> REPLACE that node_id\n"
        "4) If no strict synonym match exists -> ADD\n"
        "\n"
        "Output format (no extra text or explanation):\n"
        "- For ADD or DISCARD: output only the action in uppercase.\n"
        "- For MERGE or REPLACE: output the action in uppercase, followed by a space, then the `node_id` of the matched existing node.\n"
        "\n"
        "Example outputs:\n"
        "- MERGE <node_id>\n"
        "- REPLACE <node_id>\n"
        "- ADD\n"
        "- DISCARD\n"
        "\n"
        "No explanations. No JSON. No punctuation. No second line."
)


KGD_AMR_PROMPT = (
    "You are a product knowledge graph decision agent.\n"
    "\n"
    "Goal: Decide whether to ADD a new node, MERGE with an existing node, or REPLACE an existing node name.\n"
    "\n"
    "Relevant nodes from KG:\n"
    "{pretty_nodes}\n"
    "\n"
    "Node Type: {node_type}\n"
    "Candidate: {pretty_candidate}\n"
    "\n"
    "Choose one action from:\n"
    "- ADD: Candidate is a distinct concept not present in the KG.\n"
    "- MERGE: Candidate is the SAME concept as an existing node (true synonym), and the existing node name is the preferred form.\n"
    "- REPLACE: Candidate is the SAME concept as an existing node (true synonym), but the candidate name is the preferred/standard form and should replace the existing node name.\n"
    "\n"
    "STRICT SYNONYM POLICY (required for MERGE/REPLACE)\n"
    "Only choose MERGE or REPLACE if the candidate and an existing node are semantically identical:\n"
    "- Same meaning and scope (no broader/narrower relationship)\n"
    "- Same real-world referent (can be substituted in a sentence without changing meaning)\n"
    "- Same measurement basis/units/standards if applicable (e.g., ratings, units, dimensions)\n"
    "\n"
    "DO NOT MERGE/REPLACE if any of the following is true (choose ADD instead):\n"
    "- Candidate is related but not identical (association ≠ synonymy)\n"
    "- Candidate is a subtype/supertype, variant, feature level, or category of the existing node\n"
    "- Candidate differs by metric vs attribute (e.g., “size” vs “dimensions”; “weight” vs “mass”)\n"
    "- Candidate differs by standard/rating/threshold (e.g., “splash resistant” vs a specific IP rating unless explicitly defined as equivalent)\n"
    "- Candidate differs by mechanism (e.g., over-voltage vs over-current vs surge vs thermal protection)\n"
    "- Candidate is ambiguous while the existing node is specific, or vice versa\n"
    "\n"
    "Preferred Naming Rules (apply only after synonymy is confirmed):\n"
    "- Use the most common international or scientific name unless a local name adds significant value.\n"
    "- If candidate is better to be a representative of synonyms, choose REPLACE; otherwise choose MERGE.\n"
    "- Preserve other name variants as synonyms (handled outside this decision).\n"
    "\n"
    "Decision procedure:\n"
    "1) Evaluate candidate validity and relevance to Node Type.\n"
    "2) Check each relevant KG node for strict synonymy using the STRICT SYNONYM POLICY.\n"
    "3) If a strict synonym match exists:\n"
    "    - If existing name preferred -> MERGE with that node_id\n"
    "    - If candidate name preferred -> REPLACE that node_id\n"
    "4) If no strict synonym match exists -> ADD\n"
    "\n"
    "Output format (no extra text or explanation):\n"
    "- For ADD: output only 'ADD'\n"
    "- For MERGE or REPLACE: output the action in uppercase, followed by a space, then the `node_id` of the matched existing node.\n"
    "\n"
    "Example outputs:\n"
    "- MERGE <node_id>\n"
    "- REPLACE <node_id>\n"
    "- ADD"
)

KGD_AM_PROMPT = (
    "You are a KG node identity matcher. Decide whether to **ADD** a new node or **MERGE** the candidate with one existing node.\n"
    "\n"
    "INPUTS\n"
    "- Node Type: {node_type}\n"
    "- Candidate: {pretty_candidate}\n"
    "- Relevant Nodes: {pretty_nodes}\n"
    "\n"
    "HARD CONSTRAINTS\n"
    "1. Default = ADD. Only output MERGE when identity is certain.\n"
    "2. MERGE is allowed only for strict identity (true synonym):\n"
    "  - same concept and scope (no broader/narrower)\n"
    "  - same real-world referent; fully interchangeable in sentences\n"
    "  - if applicable, must match the same unit/standard/rating/threshold/basis\n"
    "3. Never MERGE if any of these apply (choose ADD):\n"
    "  - related but not identical (association ≠ synonym)\n"
    "  - subtype/supertype/variant/feature level/category\n"
    "  - attribute vs metric (e.g., “size” vs “dimensions”, “weight” vs “mass”)\n"
    "  - any difference or uncertainty about standard/rating (e.g., “water resistant” vs “IP67”)\n"
    "  - ambiguous candidate or ambiguous node name\n"
    "\n"
    "PROCEDURE\n"
    "1. Sanity check: candidate must be a plausible instance of node_type. If unclear → ADD.\n"
    "2. For each relevant_nodes[i], test STRICT IDENTITY:\n"
    "  - Are meanings identical?\n"
    "  - Are scope/constraints identical?\n"
    "  - Are units/standards/ratings identical (if present)?\n"
    "  - If all yes → that node is a valid merge target.\n"
    "3. If a valid merge target exists → MERGE with its node_id.\n"
    "4. Else → ADD.\n"
    "\n"
    "OUTPUT FORMAT (ABSOLUTE)\n"
    "Return exactly one line with no extra characters:\n"
    "- ADD\n"
    "- MERGE <node_id>\n"
    "\n"
    "No explanations. No JSON. No punctuation. No second line."
)

TYPE_DESC_PROMPT = (
    'You are a product taxonomy writer creating a knowledge base. Write clear, neutral, factual descriptions.\n'
    '\n'
    'Write a short knowledge-base description of this product type: {product_type!r}.\n'
    '\n'
    'Requirements\n'
    '- Length: 1-3 sentences (max 60 words)\n'
    '- Define what it is and its primary purpose\n'
    '- Mention 2-5 common features or components (only typical ones)\n'
    '- Do not mention brands, pricing, marketing language, or superlatives\n'
    '- No bullets; plain text\n'
    '- If the product type is ambiguous, choose the most common consumer meaning and do not ask questions'
)

KEY_DESC_PROMPT = (
    "You are a product taxonomy writer creating a knowledge base. Write clear, neutral, factual descriptions for attribute keys used in product catalogs.\n"
    "\n"
    "Task: Write a short knowledge-base description of the attribute key: {attribute_key!r}.\n"
    "\n"
    "Requirements:\n"
    "- Length: 1 sentence, maximum 40 words total, labeled “Description:”\n"
    "- Define what the attribute represents and its primary purpose in selecting/using the product\n"
    "- Plain text only; no bullets, no headings\n"
    "- If the attribute could apply to multiple product categories, use the most common consumer meaning and do not ask questions\n"
    "- Also provide: At least 5 example attribute values (more if useful). List them as a simple comma-separated line labeled “Examples:”, with each value capitalized as a proper noun or standard term (e.g., “Matte”, not “matte”).\n"
)


